"""added relationship between employment schedule and jobOffer

Revision ID: 0324ff9851b2
Revises: 7b42db58784a
Create Date: 2026-05-16 22:35:00.840479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0324ff9851b2'
down_revision = '7b42db58784a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE es 
        FROM employment_schedule__job_offer_link es
        LEFT JOIN job_offer jo ON es.jobOfferId = jo.id
        WHERE jo.id IS NULL;
    """)
        
    with op.batch_alter_table('employment_schedule__job_offer_link', schema=None) as batch_op:
        batch_op.alter_column('jobOfferId', 
            new_column_name='offerId',
            existing_type=mysql.INTEGER(display_width=11),
            existing_nullable=False
        )
        batch_op.create_foreign_key(None, 'job_offer', ['offerId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'employment_schedule', ['employmentScheduleId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id')

    op.rename_table('employment_schedule__job_offer_link', 'offer_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('offer_schedule', 'employment_schedule__job_offer_link')

    with op.batch_alter_table('employment_schedule__job_offer_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column(
            'offerId',
            new_column_name='jobOfferId',
            existing_type=mysql.INTEGER(display_width=11),
            existing_nullable=False,
        )
    # ### end Alembic commands ###