"""Changement de la longueur du champ de descriptionde des offres

Revision ID: 0dbb25a1e70c
Revises: 9149ef29c1de
Create Date: 2025-01-28 14:06:58.102591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dbb25a1e70c'
down_revision = '9149ef29c1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.Text(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(length=30000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
