"""Ajout de champs firstName et lastName dans la BD.

Revision ID: 1753bdb8d537
Revises: f993472800eb
Create Date: 2024-04-15 19:10:38.124786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1753bdb8d537'
down_revision = 'f993472800eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index('FK_city_idRegion')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index('FK_city_idRegion', ['idRegion'], unique=False)

    # ### end Alembic commands ###
