"""ajout_champ_creation_date_job_offer

Revision ID: 19c9e2292bce
Revises: 9149ef29c1de
Create Date: 2025-02-05 11:20:30.872941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19c9e2292bce'
down_revision = '9149ef29c1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creationDate', sa.DateTime(), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=30000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(length=30000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
        batch_op.drop_column('creationDate')

    # ### end Alembic commands ###
