"""ajout_champ_last_modified_by_an_employer_date_job_offer

Revision ID: 28465a2ba257
Revises: 19c9e2292bce
Create Date: 2025-02-05 16:06:32.834028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28465a2ba257'
down_revision = '19c9e2292bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_by_an_employer_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=30000),
               existing_nullable=False)
        batch_op.drop_column('creationDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creationDate', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.Text(length=30000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
        batch_op.drop_column('last_modified_by_an_employer_date')

    # ### end Alembic commands ###
