"""add_isApproved_column

Revision ID: 2ecee4775b61
Revises: 1753bdb8d537
Create Date: 2024-04-27 15:56:04.548531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecee4775b61'
down_revision = '1753bdb8d537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    # ### end Alembic commands ###
