"""update offerDebut

Revision ID: 4cace2e24113
Revises: 7c009c8229fa
Create Date: 2024-04-15 15:16:32.479069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cace2e24113'
down_revision = '7c009c8229fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index('FK_city_idRegion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index('FK_city_idRegion', ['idRegion'], unique=False)

    # ### end Alembic commands ###
