"""addedAprovedDateJobOffer

Revision ID: 4dc45cb0a90a
Revises: e6832be9051d
Create Date: 2024-06-10 09:16:54.424056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dc45cb0a90a'
down_revision = 'e6832be9051d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approvedDate', sa.Date(), nullable=True))
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_general_ci'),
               type_=sa.Text(length=30000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(length=30000),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_general_ci'),
               existing_nullable=False)
        batch_op.drop_column('approvedDate')

    # ### end Alembic commands ###
