"""added relationship between studyprogram and jobOffer

Revision ID: 7b42db58784a
Revises: e979f6069600
Create Date: 2026-05-16 22:09:55.933103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b42db58784a'
down_revision = 'e979f6069600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Removing offer_program that are linked to non existing job offers
    op.execute("""
        DELETE op 
        FROM offer_program op
        LEFT JOIN job_offer jo ON op.offerId = jo.id
        WHERE jo.id IS NULL;
    """)
    
    with op.batch_alter_table('offer_program', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_offer_offer_program', 'job_offer', ['offerId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_program_study_program', 'study_program', ['programId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint('fk_offer_offer_program', type_='foreignkey')
        batch_op.drop_constraint('fk_program_study_program', type_='foreignkey')
    # ### end Alembic commands ###
