"""Add OfferDebut

Revision ID: 7c009c8229fa
Revises: 8a5a8e6bfdc2
Create Date: 2024-04-15 15:15:25.207561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c009c8229fa'
down_revision = '8a5a8e6bfdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programId', sa.Integer(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint('FK_city_idRegion', type_='foreignkey')

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OfferDebut', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('salary', sa.String(length=255), nullable=False))
        batch_op.alter_column('dateEntryOffice',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('offerLink',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('employerId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('scheduleId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('urgent')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.alter_column('scheduleId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('employerId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('offerLink',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('dateEntryOffice',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('salary')
        batch_op.drop_column('OfferDebut')

    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_foreign_key('FK_city_idRegion', 'region', ['idRegion'], ['id'])

    op.drop_table('study_program')
    op.drop_table('offer_program')
    op.drop_table('employment_schedule')
    # ### end Alembic commands ###
