"""db models enterprise linked

Revision ID: 9744c493397a
Revises: b4d178d729aa
Create Date: 2026-05-18 21:36:28.619313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9744c493397a'
down_revision = 'b4d178d729aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'city', ['cityId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
