"""Modified Job Offer DateDisplay and Salary

Revision ID: a772ef2905b5
Revises: 8a5a8e6bfdc2
Create Date: 2024-04-08 14:45:44.069392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a772ef2905b5'
down_revision = '8a5a8e6bfdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateDisplayJobOffer', sa.Date(), nullable=False))
        batch_op.alter_column('salary',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('dateDisplayJobOffer')

    # ### end Alembic commands ###
