"""merged user table with employers

Revision ID: b4d178d729aa
Revises: 0324ff9851b2
Create Date: 2026-05-16 23:00:05.404887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4d178d729aa'
down_revision = '0324ff9851b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('enterpriseId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'enterprise', ['enterpriseId'], ['id'])
    
    op.execute("""
        UPDATE user u
        INNER JOIN employers e ON e.userId = u.id
        SET u.enterpriseId = e.enterpriseId
    """)

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enterpriseId', sa.Integer(), nullable=True))
        batch_op.drop_column('active')

    op.execute("""
        UPDATE job_offer jo
        INNER JOIN employers e ON e.id = jo.employerId
        SET jo.enterpriseId = e.enterpriseId
    """)
    
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column(
            'enterpriseId', 
            existing_type=sa.Integer(), 
            nullable=False
        )
        batch_op.create_foreign_key('fk_job_offer_enterprise', 'enterprise', ['enterpriseId'], ['id'])
        batch_op.drop_column('employerId')

    op.drop_table('employers')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('enterpriseId')
        batch_op.drop_column('verified')

    op.execute("""
        INSERT INTO employers (userId, verified, enterpriseId)
        SELECT id, verified, enterpriseId 
        FROM user 
        WHERE enterpriseId IS NOT NULL
    """)
    
    op.drop_constraint('fk_user_enterprise', 'user', type_='foreignkey')
    op.drop_column('user', 'enterpriseId')
    op.drop_column('user', 'verified')

    # ### end Alembic commands ###
