"""Retrait de offerStatus

Revision ID: beff9821924a
Revises: 2ecee4775b61
Create Date: 2024-04-28 19:51:07.362646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beff9821924a'
down_revision = '2ecee4775b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approbationMessage', sa.String(length=255), nullable=True))
        batch_op.drop_column('offerStatus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offerStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('approbationMessage')

    # ### end Alembic commands ###
