"""ajout de table schedule et modif jobOffer

Revision ID: cace79e373d8
Revises: 4dc45cb0a90a
Create Date: 2024-06-12 22:43:42.833029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cace79e373d8'
down_revision = '4dc45cb0a90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_schedule__job_offer_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobOfferId', sa.Integer(), nullable=False),
    sa.Column('employmentScheduleId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=30000),
               existing_nullable=False)
        batch_op.drop_column('scheduleId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduleId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.Text(length=30000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)

    op.drop_table('employment_schedule__job_offer_link')
    # ### end Alembic commands ###
