"""empty message

Revision ID: e6832be9051d
Revises: ede456978dd0
Create Date: 2024-06-04 10:37:25.766217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6832be9051d'
down_revision = 'ede456978dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=30000),
               existing_nullable=False)
        batch_op.drop_column('compliantEmployer')
        batch_op.drop_column('internship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internship', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('compliantEmployer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.Text(length=30000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
