name: Test build

on:
  push:
    branches:
      - dev
      - FE_Modification_Zach
  pull_request:
    branches:
      - dev
      - FE_Modification_Zach

jobs:
  Test_Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or any other version you want

      - name: Install dependencies
        working-directory: front-end
        run: npm i

      - name: Test Build
        working-directory: front-end
        run: vite build
