name: Build & Deploy
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: ${{secrets.DEV_SSH_HOST}}
          key: ${{secrets.DEV_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}

<<<<<<< HEAD
          script: |
            rm -r dev_project
            mkdir dev_project
            cd test_dev_project
            git clone -b dev https://github.com/ecoleduweb/ProjetApplicationH2024.git
=======
          script: 
            mkdir dev_project
            cd dev_project
            git clone -b dev git@github.com:ecoleduweb/ProjetApplicationH2024.git
>>>>>>> 9551f57098b858856d2889c50cc3556402c46076
            echo 'Deployment successful to DEV server'
