name: DEV - Build & Deploy
on:
  push:
    branches: [dev, SD_Build&Deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: ${{secrets.DEV_SSH_HOST}}
          key: ${{secrets.DEV_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}

          script: |
            rm -r dev_project
            mkdir dev_project
            cd test_dev_project
            git clone -b dev https://github.com/ecoleduweb/ProjetApplicationH2024.git
            echo 'Deployment successful to DEV server'
