name: Test BackEnd

on: [push, pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2

      - name: Install all packages
        working-directory: ProjetApplicationH2024/backend/API/tests
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libmariadb-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Create env file"
        run: |
          touch .env
          echo DATABASE_TEST_URL=${{ secrets.DATABASE_TEST_URL }} >> .env
          echo DATABASE_DEV_URL=${{ secrets.DATABASE_DEV_URL }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          cat .env

      - name: Run tests
        working-directory: tests
        run: python -m pytest
